geekshop/authapp/urls.py
from django.urls import path

import authapp.views as authapp


app_name = 'authapp'


urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('profile/', authapp.edit, name='edit'),
    path('register/', authapp.register, name='register'),
    path('vefify/<email>/<key>', authapp.verify, name='verify'),

]

geekshop/geekshop/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import include
import geekshop.views as geekshop

urlpatterns = [
    path('', include('social_django.urls', namespace='social')),
    path('', geekshop.main, name='index'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('contact/', geekshop.contact, name='contact'),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('admin_staff/', include('adminapp.urls', namespace='admin_staff')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('order/', include('ordersapp.urls', namespace='order')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    import debug_toolbar
    urlpatterns += [re_path(r'^__debug__/', include(debug_toolbar.urls))]

geekshop/ordersapp/urls.py
from django.urls import path, re_path
import ordersapp.views as ordersapp


app_name = 'ordersapp'

urlpatterns = [
    path('', ordersapp.OrderList.as_view(), name='order_list'),
    path('create/', ordersapp.OrderCreate.as_view(), name='order_create'),
    path('update/<pk>', ordersapp.OrderUpdate.as_view(), name='order_update'),
    path('delete/<pk>', ordersapp.OrderDelete.as_view(), name='order_delete'),
    path('read/<pk>', ordersapp.OrderRead.as_view(), name='order_read'),
    path('forming/complete/<pk>', ordersapp.order_forming_complete, name='order_forming_complete'),
]

geekshop/ordersapp/models.py
from django.db import models

from django.conf import settings
from mainapp.models import Product


class Order(models.Model):
    FORMING = 'FM'
    SENT_TO_PROCEED = 'STP'
    PROCEEDED = 'PRD'
    PAID = 'PD'
    READY = 'RDY'
    CANCEL = 'CNC'

    ORDER_STATUS_CHOICES = (
        (FORMING, 'формируется'),
        (SENT_TO_PROCEED, 'отправлен в обработку'),
        (PAID, 'оплачен'),
        (PROCEEDED, 'обработан'),
        (READY, 'готов к выдаче'),
        (CANCEL, 'отменен'),
    )
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    created = models.DateTimeField(verbose_name='создан', auto_now_add=True)
    updated = models.DateTimeField(verbose_name='обновлен', auto_now=True)
    status = models.CharField(verbose_name='статус',
                              max_length=3,
                              choices=ORDER_STATUS_CHOICES,
                              default=FORMING)
    is_active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)
        verbose_name = 'заказ'
        verbose_name_plural = 'заказы'

    def __str__(self):
        return 'Текущий заказ: {}'.format(self.id)

    def get_total_quantity(self):
        items = self.orderitems.select_related()
        return sum(list(map(lambda x: x.quantity, items)))

    def get_product_type_quantity(self):
        items = self.orderitems.select_related()
        return len(items)

    def get_total_cost(self):
        items = self.orderitems.select_related()
        return sum(list(map(lambda x: x.quantity * x.product.price, items)))

    def get_summary(self):
        items = self.orderitems.select_related()
        return {'get_total_cost': sum(list(map(lambda x: x.quantity * x.product.price, items))),
                'get_total_quantity': sum(list(map(lambda x: x.quantity, items)))}

    def delete(self):
        for item in self.orderitems.select_related():
            item.product.quantity += item.quantity
            item.product.save()

        self.is_active = False
        self.save()


class OrderItemQuerySet(models.QuerySet):

    def delete(self, *args, **kwargs):
        for object in self:
            object.product.quantity += object.quantity
            object.product.save()
        super().delete(*args, **kwargs)


class OrderItem(models.Model):
    objects = OrderItemQuerySet.as_manager()
    order = models.ForeignKey(Order, related_name="orderitems", on_delete=models.CASCADE)
    product = models.ForeignKey(Product, verbose_name='продукт', on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(verbose_name='количество', default=0)

    def get_product_cost(self):
        return self.product.price * self.quantity

    def delete(self):
        self.product.quantity += self.quantity
        self.product.save()
        super().delete()

geekshop/ordersapp/forms.py
from django import forms

from mainapp.models import Product
from ordersapp.models import Order, OrderItem


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        exclude = ('user',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class OrderItemForm(forms.ModelForm):
    price = forms.CharField(label='цена', required=False)

    class Meta:
        model = OrderItem
        exclude = ()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['product'].queryset = \
            Product.objects.filter(category__is_active=True, is_active=True)\
            .exclude(quantity=0)\
            .order_by('category', 'name').select_related()
        for field_name, field in self.fields.items():
            if field_name == 'product':
                field.widget.attrs['class'] = 'form-select'
                continue
            if field_name == 'quantity' and self.instance.id:
                field.widget.attrs['max'] = self.instance.product.quantity
            field.widget.attrs['class'] = 'form-control'

geekshop/ordersapp/views.py
from django.db.models.signals import pre_save
from django.dispatch import receiver
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.db import transaction

from django.forms import inlineformset_factory

from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView

from basketapp.models import Basket
from mainapp.models import Product
from ordersapp.models import Order, OrderItem
from ordersapp.forms import OrderItemForm


class FormValidMixin:
    def form_valid(self, form):
        context = self.get_context_data()
        orderitems = context['orderitems']

        with transaction.atomic():
            form.instance.user = self.request.user
            self.object = form.save()
            if orderitems.is_valid():
                orderitems.instance = self.object
                orderitems.save()

        if self.object.get_total_cost() == 0:
            self.object.delete()

        return super().form_valid(form)


class AjaxMixinGet:

    def get(self, request, *args, **kwargs):
        if request.resolver_match.url_name == 'order_create':
            self.object = None
        else:
            self.object = super().get_object()
        context = self.get_context_data()
        if self.request.is_ajax():
            product_id = self.request.GET.get('product_id')
            if product_id:
                new_product = Product.objects.filter(pk=int(product_id)).get()
                context['new_product'] = {'price': new_product.price,
                                          'quantity': new_product.quantity}
                return JsonResponse(context['new_product'])
        return self.render_to_response(context)


class OrderList(ListView):
    model = Order
    extra_context = {'title': 'заказы'}

    def get_queryset(self):
        return Order.objects.filter(user=self.request.user)


class OrderCreate(FormValidMixin, AjaxMixinGet, CreateView):
    model = Order
    fields = []
    success_url = reverse_lazy('ordersapp:order_list')
    extra_context = {'title': 'заказы/создание'}

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        OrderFormSet = inlineformset_factory(Order, OrderItem, form=OrderItemForm, extra=1)

        if self.request.POST:
            formset = OrderFormSet(self.request.POST)
        else:
            basket_items = self.request.user.basket.select_related()
            if basket_items.exists():
                OrderFormSet = inlineformset_factory(Order, OrderItem, form=OrderItemForm, extra=len(basket_items))
                formset = OrderFormSet()
                for num, form in enumerate(formset.forms):
                    form.initial['product'] = basket_items[num].product
                    form.initial['quantity'] = basket_items[num].quantity
                    form.initial['price'] = basket_items[num].product.price
                basket_items.delete()
            else:
                formset = OrderFormSet()

        context['orderitems'] = formset
        return context


class OrderUpdate(FormValidMixin, AjaxMixinGet, UpdateView):
    model = Order
    fields = []
    success_url = reverse_lazy('ordersapp:order_list')
    extra_context = {'title': 'заказы/изменение'}

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        OrderFormSet = inlineformset_factory(Order, OrderItem, form=OrderItemForm, extra=1)

        if self.request.POST:
            formset = OrderFormSet(self.request.POST, instance=self.object)
        else:
            queryset = self.object.orderitems.select_related()
            formset = OrderFormSet(instance=self.object, queryset=queryset)
            for form in formset.forms:
                if form.instance.pk:
                    form.initial['price'] = form.instance.product.price

        context['orderitems'] = formset
        return context


class OrderDelete(DeleteView):
    model = Order
    success_url = reverse_lazy('ordersapp:order_list')


class OrderRead(DetailView):
    model = Order
    extra_context = {'title': 'заказы/просмотр'}


def order_forming_complete(request, pk):
    order = get_object_or_404(Order, pk=pk)
    order.status = Order.SENT_TO_PROCEED
    order.save()

    return HttpResponseRedirect(reverse('ordersapp:order_list'))


@receiver(pre_save, sender=OrderItem)
@receiver(pre_save, sender=Basket)
def product_quantity_update_save(sender, instance, **kwargs):
    if instance.pk:
        instance.product.quantity -= instance.quantity - sender.objects.get(pk=instance.pk).quantity
    else:
        instance.product.quantity -= instance.quantity
    instance.product.save()

geekshop/ordersapp/templates/ordersapp/order_confirm_delete.html
{% extends 'base.html' %}
{% load static %}
{% block menu %}
    {% include 'includes/inc_main_links.html' %}
{% endblock %}
{% block content %}
    <div class="category_delete">
        <div class="h1 d-flex justify-content-center">Уверены, что хотите удалить?</div>
        {% include 'ordersapp/includes/inc_order_summary.html' %}
        <div class="d-flex justify-content-around">
            <form action="{% url 'ordersapp:order_delete' object.pk %}" method="post">
                {% csrf_token %}
                <input class="btn btn-danger" type="submit" value="Удалить">
            </form>
            <a class="btn btn-success" href="{% url 'ordersapp:order_list' %}">Отмена</a>
        </div>
    </div>
{% endblock %}

geekshop/ordersapp/templates/ordersapp/order_detail.html
{% extends 'base.html' %}
{% load static %}
{% load media_tags %}
{% block menu %}
    {% include 'includes/inc_main_links.html' %}
{% endblock %}
{% block content %}
    {% include 'ordersapp/includes/inc_order_summary.html' %}
    <div class="basket_list">
        <div class="row" style="justify-content:center">
            <div class="table-responsive">
                <table class="table table-hover text-center">
                    <thead class="table-dark">
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Фото</th>
                        <th scope="col">Категория</th>
                        <th scope="col">Имя</th>
                        <th scope="col">Цена</th>
                        <th scope="col">Qty</th>
                        <th scope="col">Стоимость</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for item in object.orderitems.select_related %}
                        <tr>
                            <th class="align-middle" scope="row">{{ forloop.counter }}</th>
                            <td style="width: 25%"><img src="{{ item.product.image|media_products }}"
                                     alt="{{ item.product.short_desc }}" class="img-fluid" style="width: 50%"></td>
                            <td class="align-middle">{{ item.product.category.name }}</td>
                            <td class="align-middle">{{ item.product.name }}</td>
                            <td class="align-middle">{{ item.product.price }}&nbspруб</td>
                            <td class="align-middle">x {{ item.quantity }}</td>
                            <td class="align-middle"> = {{ item.get_product_cost }}&nbspруб</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    {% include 'ordersapp/includes/inc_order_actions.html' %}

{% endblock %}

geekshop/ordersapp/templates/ordersapp/order_form.html
{% extends 'base.html' %}
{% load static %}
{% load cache %}
{% block js %}
    <script src="{% static 'js/jquery.formset.js' %}"></script>
    <script src="{% static 'js/order_script.js' %}"></script>
{% endblock %}
{% block menu %}
    {% include 'includes/inc_main_links.html' %}
{% endblock %}
{% block content %}
    {% include 'ordersapp/includes/inc_order_summary.html' %}
    <div class="order_form">
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <table class="table">
                {{ orderitems.management_form }}
                {% for form in orderitems.forms %}
                    {% if forloop.first %}
                        <thead>
                        <tr>
                            {% for field in form.visible_fields %}
                                <th class="{% cycle 'td1' 'td2' 'td3' 'td4' %} order formset_td">
                                    {{ field.label|capfirst }} {% if field.name == 'price' %}/ руб {% endif %}
                                </th>
                            {% endfor %}
                        </tr>
                        </thead>
                    {% endif %}
                    <tr class="formset_row">
                        {% for field in form.visible_fields %}
                            <td class="{% cycle 'td1' 'td2' 'td3' 'td4' %} order formset_td">
                                {% if forloop.first %}
                                    {% for hidden in form.hidden_fields %}
                                        {{ hidden }}
                                    {% endfor %}
                                {% endif %}
                                {{ field.errors.as_ul }}
                                {% if field.name == 'price' %}
                                    <span class="orderitems-{{ forloop.parentloop.counter0 }}-price">
                                    {{ field.value|default:'' }}
                                    </span>
                                {% elif field.name == 'product' %}
                                    {% cache 3600 orderitemform_product field.value %}
                                        {{ field }}
                                    {% endcache %}
                                {% else %}
                                    {{ field }}
                                {% endif %}
                            </td>
                        {% endfor %}
                    </tr>
                {% endfor %}
            </table>
            {% include 'ordersapp/includes/inc_order_actions.html' %}
        </form>
    </div>
{% endblock %}

geekshop/ordersapp/templates/ordersapp/order_list.html
{% extends 'base.html' %}
{% load static %}
{% block menu %}
    {% include 'includes/inc_main_links.html' %}
{% endblock %}
{% block content %}
    {% if object_list %}
        <div class="row" style="justify-content:center">
            <table class="table table-bordered table-hover text-center caption-top">
                <caption class="h2">
                    Ваши заказы,
                    {% if user.first_name %}
                        {{ user.first_name|title }}
                    {% else %}
                        Пользователь
                    {% endif %}
                </caption>
                <thead class="table-dark">
                <tr>
                    <th scope="col">ID</th>
                    <th scope="col">Создан</th>
                    <th scope="col">Обновлен</th>
                    <th scope="col">Статус</th>
                    <th scope="col">Опции</th>
                </tr>
                </thead>
                <tbody>
                {% for item in object_list %}
                    {% if item.is_active %}
                        <tr>
                            <th class="align-middle" scope="row">{{ item.pk }}</th>
                            <td class="align-middle">{{ item.created|date:"d-m-Y H:i:s" }}</td>
                            <td class="align-middle">{{ item.updated|date:"d-m-Y H:i:s" }}</td>
                            <td class="align-middle">{{ item.get_status_display|capfirst }}</td>
                            <td class="d-flex justify-content-around">
                                <a href="{% url 'ordersapp:order_read' item.pk %}" class="btn btn-outline-primary">
                                    Посмотреть
                                </a>
                                <a class="btn btn-outline-warning {% if item.status != 'FM' %} disabled {% endif %}"
                                   href="{% url 'ordersapp:order_update' item.pk %}">
                                    Редактировать
                                </a>
                                <a class="btn btn-outline-danger {% if item.status != 'FM' %} disabled {% endif %}"
                                   href="{% url 'ordersapp:order_delete' item.pk %}">
                                    Удалить
                                </a>
                            </td>
                        </tr>
                    {% endif %}
                {% endfor %}
                </tbody>
            </table>
        </div>
    {% endif %}
        <a class="btn btn-primary" href="{% url 'ordersapp:order_create' %}">
            Новый
        </a>
{% endblock %}