geekshop/adminapp/urls.py
import adminapp.views as adminapp
from django.urls import path


app_name = 'adminapp'

urlpatterns = [

    path('users/create/', adminapp.UserCreateView.as_view(), name='user_create'),
    path('users/read/', adminapp.UsersListView.as_view(), name='users'),
    path('users/update/<int:pk>/', adminapp.UserUpdateView.as_view(), name='user_update'),
    path('users/delete/<int:pk>/', adminapp.UserDeleteView.as_view(), name='user_delete'),

    path('categories/create/', adminapp.CategoryCreateView.as_view(), name='category_create'),
    path('categories/read/', adminapp.CategoriesListView.as_view(), name='categories'),
    path('categories/update/<int:pk>/', adminapp.CategoryUpdateView.as_view(), name='category_update'),
    path('categories/delete/<int:pk>/', adminapp.CategoryDeleteView.as_view(), name='category_delete'),

    path('products/create/category/<int:pk>/', adminapp.ProductCreateView.as_view(), name='product_create'),
    path('products/read/category/<int:pk>/', adminapp.ProductsListView.as_view(), name='products'),
    path('products/read/<int:pk>/', adminapp.ProductDetailedView.as_view(), name='product_read'),
    path('products/update/<int:pk>/', adminapp.ProductUpdateView.as_view(), name='product_update'),
    path('products/delete/<int:pk>/', adminapp.ProductDeleteView.as_view(), name='product_delete'),
]

geekshop/authapp/urls.py
from django.urls import path

import authapp.views as authapp


app_name = 'authapp'


urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('profile/', authapp.edit, name='edit'),
    path('register/', authapp.register, name='register'),
    path('vefify/<email>/<key>', authapp.verify, name='verify'),

]

geekshop/basketapp/urls.py
from django.urls import path
import basketapp.views as basketapp

app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.basket, name='view'),
    path('add/<int:pk>/', basketapp.basket_add, name='add'),
    path('remove/<int:pk>/', basketapp.basket_remove, name='remove'),
    path('edit/<int:pk>/<int:quantity>/', basketapp.basket_edit, name='edit'),
]

geekshop/geekshop/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import include
import geekshop.views as geekshop

urlpatterns = [
    path('', include('social_django.urls', namespace='social')),
    path('', geekshop.main, name='index'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('contact/', geekshop.contact, name='contact'),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('admin_staff/', include('adminapp.urls', namespace='admin_staff')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('order/', include('ordersapp.urls', namespace='order')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    import debug_toolbar
    urlpatterns += [re_path(r'^__debug__/', include(debug_toolbar.urls))]

geekshop/mainapp/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from .views import detail, ProductsView

app_name = 'mainapp'

urlpatterns = [
   path('', ProductsView.as_view(), name='category'),
   path('category/<int:pk>', ProductsView.as_view(), name='category'),
   path('product/<int:pk>', detail, name='details'),
   path('category/<int:pk>/ajax', ProductsView.as_view()),
   path('category/<int:pk>?page=<int:page>)/ajax', ProductsView.as_view()),
]

geekshop/ordersapp/urls.py
from django.urls import path, re_path
import ordersapp.views as ordersapp


app_name = 'ordersapp'

urlpatterns = [
    path('', ordersapp.OrderList.as_view(), name='order_list'),
    path('create/', ordersapp.OrderCreate.as_view(), name='order_create'),
    path('update/<pk>', ordersapp.OrderUpdate.as_view(), name='order_update'),
    path('delete/<pk>', ordersapp.OrderDelete.as_view(), name='order_delete'),
    path('read/<pk>', ordersapp.OrderRead.as_view(), name='order_read'),
    path('forming/complete/<pk>', ordersapp.order_forming_complete, name='order_forming_complete'),
]

geekshop/geekshop/views.py
from django.shortcuts import render
from mainapp.models import Product


def main(request):
    title = 'главная'

    context = {
        'title': title,
        'products': Product.objects.filter(category__is_active=True, is_active=True)[:3],
    }
    return render(request, 'index.html', context)


def contact(request):
    title = 'контакты'
    context = {
        'title': title,
        'contact_number': range(3)
    }

    return render(request, 'contact.html', context)

geekshop/geekshop/templates/geekshop/includes/inc_contact_card.html
{% for i in contact_number %}
    <div class="location-1">
        <i class="fa fa-map-marker fa-5x"></i>
        <h4>Москва</h4>
        <div class="contacts">
            <h5>Телефон</h5>
            <p>+7-888-888-8888</p>
        </div>
        <div class="contacts">
            <h5>Email</h5>
            <p>info@geekshop.ru</p>
        </div>
        <div class="contacts">
            <h5>Адрес</h5>
            <p>В пределах МКАД</p>
        </div>
    </div>
{% endfor %}

geekshop/geekshop/templates/geekshop/includes/inc_featured_content.html
{%  load static %}
 <div class="featured">
     <div class="featured-menu">
         <a class="active" href="#">Популярные</a><a href="#">Новинки</a>
     </div>
     <a class="explore" href="{% url 'products:category' 1 %}">показать все <img src="{% static 'img/arrow.png' %}" alt="img"></a>
     <div class="clearfix">
     </div>
     <div class="tab-content">
         {% for product in products %}
            <div class="block">
                <a href="{% url 'products:details' product.id %}">
                    <img src="/media/{{ product.image|default:'img/default.jpg' }}" alt="img" style="max-width: 270px">
                    <div class="text">
                        <img src="{% static 'img/icon-hover.png' %}" alt="img">
                        <h4>{{ product.name }}</h4>
                        <p>{{ product.short_desc }}</p>
                    </div>
                </a>
            </div>
         {% endfor %}
     </div>
 </div>

geekshop/geekshop/templates/geekshop/includes/inc_main_links.html
<div class="header clearfix">
    <a href="{% url 'index' %}" class="logo"></a>
    <ul class="menu">
        {% for link in main_links %}
            {% if link.href == request.resolver_match.url_name or request.resolver_match.namespaces.0 in link.href %}
                <li><a href="{% url link.href %}" class="active">{{ link.name }}</a></li>
            {% else %}
                <li><a href="{% url link.href %}">{{ link.name }}</a></li>
            {% endif %}
        {% endfor %}
        {% if user.is_authenticated %}
            <li>
                <div class="dropdown ">
                    <a href="#" class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        {{ user.first_name|default:'Пользователь' }} <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                        <li><a class="dropdown-item" href="{% url 'auth:edit' %}">профиль</a></li>
                        <li><a class="dropdown-item" href="{% url 'order:order_list' %}">заказы</a></li>
                    </ul>
                </div>
            </li>
        {% endif %}
        {% if user.is_superuser %}
            <li>
                <a href="{% url 'admin_staff:users' %}">админка</a>
            </li>
        {% endif %}
        <li>
            {% if user.is_authenticated %}
                <a href="{% url 'auth:logout' %}">выйти</a>
            {% else %}
                <a href="{% url 'auth:login' %}">войти</a>
            {% endif %}
        </li>
    </ul>
    <div class="basket-container">
        <a href="#" class="search"></a>
        {% if basket %}
            {% with object_summary=basket.0.get_summary %}
                <a href="{% url 'basket:view' %}" class="basket">
                    <span>{{ object_summary.total_price|floatformat:0 }} руб ({{ object_summary.total_amount }} шт.)</span>
                </a>
            {% endwith %}
        {% endif %}
    </div>

</div>