geekshop/authapp/urls.py
from django.urls import path

import authapp.views as authapp


app_name = 'authapp'


urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('profile/', authapp.edit, name='edit'),
    path('register/', authapp.register, name='register'),
    path('vefify/<email>/<key>', authapp.verify, name='verify'),

]

geekshop/basketapp/urls.py
from django.urls import path
import basketapp.views as basketapp

app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.basket, name='view'),
    path('add/<int:pk>/', basketapp.basket_add, name='add'),
    path('remove/<int:pk>/', basketapp.basket_remove, name='remove'),
    path('edit/<int:pk>/<int:quantity>/', basketapp.basket_edit, name='edit'),
]

geekshop/geekshop/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import include
import geekshop.views as geekshop

urlpatterns = [
    path('', include('social_django.urls', namespace='social')),
    path('', geekshop.main, name='index'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('contact/', geekshop.contact, name='contact'),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('admin_staff/', include('adminapp.urls', namespace='admin_staff')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('order/', include('ordersapp.urls', namespace='order')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    import debug_toolbar
    urlpatterns += [re_path(r'^__debug__/', include(debug_toolbar.urls))]

geekshop/mainapp/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from .views import detail, ProductsView

app_name = 'mainapp'

urlpatterns = [
   path('', ProductsView.as_view(), name='category'),
   path('category/<int:pk>', ProductsView.as_view(), name='category'),
   path('product/<int:pk>', detail, name='details'),
   path('category/<int:pk>/ajax', ProductsView.as_view()),
   path('category/<int:pk>?page=<int:page>)/ajax', ProductsView.as_view()),
]

geekshop/mainapp/models.py
from django.db import models


# Create your models here.
class ProductCategories(models.Model):
    name = models.CharField(verbose_name='имя', max_length=64, unique=True)
    is_active = models.BooleanField(verbose_name='активна', default=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(ProductCategories, on_delete=models.CASCADE, verbose_name='категория')
    name = models.CharField(verbose_name='имя', max_length=64, unique=True)
    short_desc = models.CharField(verbose_name='краткое описание', max_length=64, blank=True)
    desc = models.TextField(verbose_name='описание', blank=True)
    price = models.DecimalField(verbose_name='цена продукта', max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(verbose_name='количество на складе', default=0)
    image = models.ImageField(verbose_name='картинка', upload_to='img', blank=True)
    is_active = models.BooleanField(verbose_name='в каталоге', default=True)

    def __str__(self):
        return f'{self.name} ({self.category.name})'

geekshop/mainapp/views.py
import random

from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404
from django.template.loader import render_to_string
from django.views.generic import ListView

from .models import ProductCategories, Product

from django.conf import settings
from django.core.cache import cache


def get_products():
    if settings.LOW_CACHE:
        key = 'products'
        products = cache.get(key)
        if products is None:
            products = \
                Product.objects.all().exclude(category__is_active=False).exclude(is_active=False)\
                    .select_related('category')
            cache.set(key, products)
        return products
    else:
        return Product.objects.all().exclude(category__is_active=False).exclude(is_active=False)\
            .select_related('category')


def get_product(pk):
    if settings.LOW_CACHE:
        key = f'product_{pk}'
        product = cache.get(key)
        if product is None:
            product = get_object_or_404(Product, pk=pk)
            cache.set(key, product)
        return product
    else:
        return get_object_or_404(Product, pk=pk)


def get_products_in_cat(pk):
    if settings.LOW_CACHE:
        key = f'products_in_cat_{pk}'
        products = cache.get(key)
        if products is None:
            products = Product.objects.filter(category_id__pk=pk).exclude(category__is_active=False, is_active=False)
            cache.set(key, products)
        return products
    else:
        return Product.objects.filter(category_id__pk=pk).exclude(category__is_active=False, is_active=False)


def get_category(pk):
    if settings.LOW_CACHE:
        key = f'category_{pk}'
        category = cache.get(key)
        if category is None:
            category = get_object_or_404(ProductCategories, pk=pk)
            cache.set(key, category)
        return category
    else:
        return get_object_or_404(ProductCategories, pk=pk)


def get_hot_product():
    products = get_products()
    return random.sample(list(products), 1)[0]


def get_same_products(hot_product):
    if settings.LOW_CACHE:
        key = f'{hot_product.category}_{hot_product.pk}'
        same_products = cache.get(key)
        if same_products is None:
            same_products = Product.objects.filter(category=hot_product.category).exclude(pk=hot_product.pk)[:3]
            cache.set(key, same_products)
        return same_products
    else:
         return Product.objects.filter(category=hot_product.category).exclude(pk=hot_product.pk)[:3]


class ProductsView(ListView):
    template_name = 'mainapp/products_list.html'
    extra_context = {'title': 'каталог'}
    paginate_by = 3
    context_object_name = 'products'

    def get_queryset(self):
        if 'pk' in self.kwargs.keys():
            if self.kwargs['pk'] == 1:
                return get_products()
            else:
                return get_products_in_cat(self.kwargs['pk'])
        same_products = get_same_products(self.hot_product)
        return same_products

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if 'pk' in self.kwargs.keys():
            if self.kwargs['pk'] == 1:
                context['category'] = {'name': 'все'}
            else:
                context['category'] = get_category(self.kwargs['pk'])
            return context
        context['product'] = self.hot_product
        return context

    def get(self, request, *args, **kwargs):
        self.hot_product = get_hot_product()
        self.object_list = self.get_queryset()
        context = self.get_context_data(**kwargs)
        if 'product' in context.keys():
            self.template_name = 'mainapp/products.html'
        if self.request.is_ajax():
            result = render_to_string('mainapp/includes/inc_cat_products_list.html', context, request=request)
            return JsonResponse({'result': result})
        return self.render_to_response(context)


def detail(request, pk=None):
    title = 'продукт'
    content = {
        'title': title,
        'product': get_product(pk),
    }

    return render(request, 'mainapp/products.html', content)

geekshop/mainapp/templates/mainapp/includes/inc_cat_products_list.html
{% load static %}
<div class="links clearfix">
    {% include 'mainapp/includes/inc_product_cat.html' %}
</div>
<div class="products_list">
    <div class="title clearfix">
        <h2>
            Категория: "{{ category.name|title }}"
        </h2>
    </div>
    <div class="category-products clearfix">

        {% for product in products %}
            <div class="block">
                <a href="{% url 'products:details' product.id %}">
                    <img src="/media/{{ product.image|default:'img/default.jpg' }}" alt="product">
                    <div class="text">
                        <img src="{% static 'img/icon-hover.png' %}" alt="hover">
                        <h4>{{ product.name }}</h4>
                        <p>{{ product.desc }}</p>
                    </div>
                </a>
            </div>
        {% endfor %}

    </div>
</div>
{% if is_paginated %}
    <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
            <li class="page-item"><a class="page-link"
                                     href="?page={{ page_obj.previous_page_number }}">Previous</a>
            </li>
        {% else %}
            <li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
        {% endif %}
        {% for i in paginator.page_range %}
            {% if page_obj.number == i %}
                <li class="page-item active"><a class="page-link" href="#">{{ i }}</a></li>
            {% else %}
                <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
            {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#">Next</a>
            </li>
        {% endif %}
    </ul>
{% endif %}

geekshop/mainapp/templates/mainapp/includes/inc_product.html
{% load static %}
<div class="details-products">
    <div class="details-slider">
        <div class="slider-product">
            <img src="/media/{{ product.image|default:'img/default.jpg' }}" alt="img" style="width:100%">
        </div>
        <div class="slider-control">
            {% for i in '123' %}
                <div class="block">
                    <a href="#"><img src="/media/{{ product.image|default:'img/default.jpg' }}" alt="{{ product.name }}" style="width:100%">
                        <div class="text"></div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
    <div class="description">
        <h3 class="big-bold">{{ product.name }}</h3>
        <h3 class="red">
            {% if not request.resolver_match.url_name == 'details' %}
                горячее предложение
            {% endif %}
        </h3>
        <p class="price"> {{ product.price }} <span>руб</span></p>
        <a href="{% url 'basket:add' product.id %}" class="red-button">
            заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
        </a>
        <div class="description-text">
            {{ product.desc }}
        </div>
    </div>
</div>

geekshop/mainapp/templates/mainapp/includes/inc_product_cat.html
<ul class="links-menu">
    {% for category in categories %}
        {% if category.is_active %}
            {% if category.id == request.resolver_match.kwargs.pk and request.resolver_match.url_name != 'details'%}
                <li><a href="{% url 'products:category' category.id %}" class="active">{{ category.name }}</a></li>
            {% elif request.resolver_match.url_name == 'details' and category.id == product.category.id %}
                <li><a href="{% url 'products:category' category.id %}" class="active">{{ category.name }}</a></li>
            {% else %}
                <li><a href="{% url 'products:category' category.id %}">{{ category.name }}</a></li>
            {% endif %}
        {% endif %}
    {% endfor %}
</ul>

geekshop/mainapp/templates/mainapp/includes/inc_proguct_cat.html
<ul class="links-menu">
    {% for category in categories %}
        {% if category.is_active %}
            {% if category.id == request.resolver_match.kwargs.pk and request.resolver_match.url_name != 'details'%}
                <li><a href="{% url 'products:category' category.id %}" class="active">{{ category.name }}</a></li>
            {% elif request.resolver_match.url_name == 'details' and category.id == product.category.id %}
                <li><a href="{% url 'products:category' category.id %}" class="active">{{ category.name }}</a></li>
            {% else %}
                <li><a href="{% url 'products:category' category.id %}">{{ category.name }}</a></li>
            {% endif %}
        {% endif %}
    {% endfor %}
</ul>

geekshop/mainapp/templates/mainapp/includes/inc_related_products.html
{% load static %}
<div class="related">
    <div class="title clearfix">
        <h2>Похожие продукты</h2>
        <a class="explore" href="#">показать все <img src="{% static 'img/arrow.png' %}" alt="img"></a>
    </div>
    <div class="related-products clearfix">
        {% for product in products %}
            <div class="block">
                <a href="{% url 'products:details' product.id %}">
                    <img src="/media/{{ product.image|default:'img/default.jpg' }}" alt="{{ product.name }}">
                    <div class="text">
                        <img src="{% static 'img/icon-hover.png' %}" alt="img">
                        <h4>{{ product.name }}</h4>
                        <p>{{ product.short_desc }}</p>
                    </div>
                </a>
            </div>
        {% endfor %}
    </div>
</div>