geekshop/adminapp/urls.py
import adminapp.views as adminapp
from django.urls import path


app_name = 'adminapp'

urlpatterns = [

    path('users/create/', adminapp.UserCreateView.as_view(), name='user_create'),
    path('users/read/', adminapp.UsersListView.as_view(), name='users'),
    path('users/update/<int:pk>/', adminapp.UserUpdateView.as_view(), name='user_update'),
    path('users/delete/<int:pk>/', adminapp.UserDeleteView.as_view(), name='user_delete'),

    path('categories/create/', adminapp.CategoryCreateView.as_view(), name='category_create'),
    path('categories/read/', adminapp.CategoriesListView.as_view(), name='categories'),
    path('categories/update/<int:pk>/', adminapp.CategoryUpdateView.as_view(), name='category_update'),
    path('categories/delete/<int:pk>/', adminapp.CategoryDeleteView.as_view(), name='category_delete'),

    path('products/create/category/<int:pk>/', adminapp.ProductCreateView.as_view(), name='product_create'),
    path('products/read/category/<int:pk>/', adminapp.ProductsListView.as_view(), name='products'),
    path('products/read/<int:pk>/', adminapp.ProductDetailedView.as_view(), name='product_read'),
    path('products/update/<int:pk>/', adminapp.ProductUpdateView.as_view(), name='product_update'),
    path('products/delete/<int:pk>/', adminapp.ProductDeleteView.as_view(), name='product_delete'),
]

geekshop/authapp/urls.py
from django.urls import path

import authapp.views as authapp


app_name = 'authapp'


urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('profile/', authapp.edit, name='edit'),
    path('register/', authapp.register, name='register'),
    path('vefify/<email>/<key>', authapp.verify, name='verify'),

]

geekshop/geekshop/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import include
import geekshop.views as geekshop

urlpatterns = [
    path('', include('social_django.urls', namespace='social')),
    path('', geekshop.main, name='index'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('contact/', geekshop.contact, name='contact'),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('admin_staff/', include('adminapp.urls', namespace='admin_staff')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('order/', include('ordersapp.urls', namespace='order')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    import debug_toolbar
    urlpatterns += [re_path(r'^__debug__/', include(debug_toolbar.urls))]

geekshop/adminapp/models.py
from django.db import models

# Create your models here.

geekshop/adminapp/forms.py
from django import forms
from authapp.models import ShopUser
from authapp.forms import ShopUserEditForm
from mainapp.models import ProductCategories, Product


class ShopUserAdminEditForm(ShopUserEditForm):
    class Meta:
        model = ShopUser
        fields = '__all__'


class ProductCategoryEditForm(forms.ModelForm):
    class Meta:
        model = ProductCategories
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if field_name == 'is_active':
                field.widget.attrs['class'] = 'form-check-input'
                continue
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

    def clean_name(self):
        data = self.cleaned_data['name']
        if not data:
            raise forms.ValidationError("Нельзя создать категорию без имени!")

        return data


class ProductEditForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if field_name == 'is_active':
                field.widget.attrs['class'] = 'form-check-input'
                continue
            if field_name == 'category':
                field.widget.attrs['class'] = 'form-select'
                continue
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

    def clean_name(self):
        data = self.cleaned_data['name']
        if not data:
            raise forms.ValidationError("Нельзя создать продукт без имени!")

        return data

    def clean_category(self):
        data = self.cleaned_data['category']
        if not data:
            raise forms.ValidationError("Нельзя создать продукт без категории!")

        return data

geekshop/adminapp/views.py
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView

from authapp.forms import ShopUserRegisterForm
from authapp.models import ShopUser
from django.shortcuts import HttpResponseRedirect
from mainapp.models import Product, ProductCategories
from django.contrib.auth.decorators import user_passes_test
from adminapp.forms import ShopUserAdminEditForm, ProductCategoryEditForm, ProductEditForm


@method_decorator(user_passes_test(lambda u: u.is_superuser), name='dispatch')
class UsersListView(ListView):
    model = ShopUser
    template_name = 'adminapp/users.html'
    context_object_name = 'users_list'
    ordering = ['-is_active', '-is_superuser', '-is_staff', 'username']
    extra_context = {'title': 'админка/пользователи'}


@method_decorator(user_passes_test(lambda u: u.is_superuser), name='dispatch')
class UserCreateView(CreateView):
    model = ShopUser
    template_name = 'adminapp/user_update.html'
    form_class = ShopUserRegisterForm
    success_url = reverse_lazy('admin_staff:users')
    extra_context = {'title': 'пользователи/создание'}


@method_decorator(user_passes_test(lambda u: u.is_superuser), name='dispatch')
class UserUpdateView(UpdateView):
    model = ShopUser
    template_name = 'adminapp/user_update.html'
    form_class = ShopUserAdminEditForm
    extra_context = {'title': 'пользователи/редактирование'}

    def get_success_url(self):
        return reverse_lazy('admin_staff:user_update', args=[self.object.pk])


@method_decorator(user_passes_test(lambda u: u.is_superuser), name='dispatch')
class UserDeleteView(DeleteView):
    model = ShopUser
    success_url = reverse_lazy('admin_staff:users')

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = False
        self.object.save()

        return HttpResponseRedirect(self.get_success_url())


@method_decorator(user_passes_test(lambda u: u.is_superuser), name='dispatch')
class CategoriesListView(ListView):
    model = ProductCategories
    template_name = 'adminapp/categories.html'
    extra_context = {'title': 'админка/категории'}
    context_object_name = 'categories'


@method_decorator(user_passes_test(lambda u: u.is_superuser), name='dispatch')
class CategoryCreateView(CreateView):
    model = ProductCategories
    template_name = 'adminapp/category_update.html'
    form_class = ProductCategoryEditForm
    extra_context = {'title': 'категории/создание'}
    success_url = reverse_lazy('admin_staff:categories')


@method_decorator(user_passes_test(lambda u: u.is_superuser), name='dispatch')
class CategoryUpdateView(UpdateView):
    model = ProductCategories
    template_name = 'adminapp/category_update.html'
    form_class = ProductCategoryEditForm
    extra_context = {'title': 'категории/редактирование'}

    def get_success_url(self):
        return reverse_lazy('admin_staff:category_update', args=[self.object.pk])


@method_decorator(user_passes_test(lambda u: u.is_superuser), name='dispatch')
class CategoryDeleteView(DeleteView):
    model = ProductCategories
    success_url = reverse_lazy('admin_staff:categories')

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = False
        self.object.save()

        return HttpResponseRedirect(self.get_success_url())


@method_decorator(user_passes_test(lambda u: u.is_superuser), name='dispatch')
class ProductsListView(ListView):
    model = Product
    template_name = 'adminapp/products.html'
    paginate_by = 4
    context_object_name = 'products'
    extra_context = {'title': 'админка/продукты'}

    def get_queryset(self):
        pk = self.kwargs['pk']
        if pk == 1:
            return Product.objects.all().order_by('name')
        return Product.objects.filter(category__pk=pk).order_by('name')


@method_decorator(user_passes_test(lambda u: u.is_superuser), name='dispatch')
class ProductCreateView(CreateView):
    model = Product
    extra_context = {'title': 'продукты/создание'}
    form_class = ProductEditForm
    template_name = 'adminapp/product_update.html'

    def get_initial(self):
        return {'category': self.kwargs['pk']}

    def get_success_url(self):
        return reverse_lazy('admin_staff:products', args=[self.object.category.id])


@method_decorator(user_passes_test(lambda u: u.is_superuser), name='dispatch')
class ProductDetailedView(DetailView):
    model = Product
    extra_context = {'title': 'продукты/детали'}
    template_name = 'adminapp/product_read.html'


@method_decorator(user_passes_test(lambda u: u.is_superuser), name='dispatch')
class ProductUpdateView(UpdateView):
    model = Product
    extra_context = {'title': 'продукты/редактирование'}
    template_name = 'adminapp/product_update.html'
    form_class = ProductEditForm

    def get_success_url(self):
        return reverse_lazy('admin_staff:product_update', args=[self.object.pk])


@method_decorator(user_passes_test(lambda u: u.is_superuser), name='dispatch')
class ProductDeleteView(DeleteView):
    model = Product

    def get_success_url(self):
        return reverse_lazy('admin_staff:products', args=[self.object.category.id])

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = False
        self.object.save()

        return HttpResponseRedirect(self.get_success_url())

geekshop/adminapp/templates/adminapp/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
            {{ title|title }}
        {% endblock %}
    </title>
    <link rel="stylesheet" type="text/css"
          href='https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css'>
    <link rel="stylesheet" href='https://cdn.jsdelivr.net/npm/boxicons@latest/css/boxicons.min.css'>
    <link rel="stylesheet" type="text/css" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src='https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js'></script>
    <script src="{% static 'js/admin_scripts.js' %}"></script>

    {% block css %}
    {% endblock %}

    {% block js %}
    {% endblock %}
</head>
<body id="body-pd">
<header class="header" id="header">
    <div class="header_toggle">
        <i class='bx bx-menu' id="header-toggle"></i>
    </div>
    <div class="header_img">
        <img src="/media/{{ request.user.avatar|default:'users_avatars/default_avatar.svg' }}" alt="avatar">
    </div>
</header>
<div class="l-navbar" id="nav-bar">
    <nav class="nav">
        <div>
            <a href="{% url 'index' %}" class="nav_logo">
                <i class='bx bx-layer nav_logo-icon'></i>
                <span class="nav_logo-name">На сайт</span>
            </a>
            {% include 'adminapp/includes/inc_admin_sidebar.html' %}
        </div>
{#        <a href="#" class="nav_link">#}
{#            <i class='bx bx-log-out nav_icon'></i>#}
{#            <span class="nav_name">SignOut</span>#}
{#        </a>#}
    </nav>
</div>
<!--Container Main start-->
<div>
    {% block main_content %}
    {% endblock %}
</div>
<!--Container Main end-->
{% if is_paginated %}

  <ul class="pagination justify-content-center">
    {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
    {% else %}
      <li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
    {% endif %}
    {% for i in paginator.page_range %}
      {% if page_obj.number == i %}
        <li class="page-item active"><a class="page-link" href="#">{{ i }}</a></li>
      {% else %}
        <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
    {% else %}
       <li class="page-item disabled">
      <a class="page-link" href="#">Next</a>
    </li>
    {% endif %}
  </ul>
{% endif %}
</body>
</html>

geekshop/adminapp/templates/adminapp/categories.html
{% extends 'adminapp/base.html' %}
{% load static %}
{% block main_content %}
    <table class="table table-bordered table-hover caption-top align-middle text-center">
        <caption>
            <a href="{% url 'admin_staff:category_create' %}"
               class="btn btn-primary">Добавить категорию</a>
        </caption>
        <thead class="table-dark">
        <tr>
            <th scope="col">Категория</th>
            <th scope="col">Активный</th>
            <th scope="col">Опции</th>
        </tr>
        </thead>
        <tbody>
        {% for category in categories %}
            <tr {% if not category.is_active %}style="opacity: 0.5"{% endif %}>
                <th scope="row">
                    <a href="{% url 'admin_staff:category_update' category.id %}"
                       class="link-info">{{ category.name }}</a></th>
                <td>
                    {% if category.is_active %}
                        <i class="fa fa-check-circle"></i>
                    {% else %}
                        <i class="fa fa-times-circle"></i>
                    {% endif %}
                </td>
                <td>
                    <div class="d-flex justify-content-around">
                        <form action="{% url 'admin_staff:products' category.id %}" method="GET">
                            {% csrf_token %}
                            <button class="btn btn-outline-primary">Продукты</button>
                        </form>
                        <form action="{% url 'admin_staff:category_delete' category.id %}" method="POST">
                            {% csrf_token %}
                            {% if category.is_active %}
                                <button class="btn btn-outline-danger">Удалить</button>
                            {% else %}
                                <button class="btn btn-outline-danger disabled">Удалить</button>
                            {% endif %}
                        </form>
                    </div>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

geekshop/adminapp/templates/adminapp/category_update.html
{% extends 'adminapp/base.html' %}
{% load static %}
{% block main_content %}
    <div class="col-5 mx-left">
        <div class="row">
            <form class="form-control" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <input class="form-control bnt-primary" type="submit" value="сохранить">
            </form>
            <button class="btn btn-round form-control last">
                <a href="{% url 'admin_staff:categories' %}">
                    К списку категорий
                </a>
            </button>
        </div>
    </div>
{% endblock %}

geekshop/adminapp/templates/adminapp/product_read.html
{% extends 'adminapp/base.html' %}
{% load static %}
{% load verbouse_name %}
{% block main_content %}
    <div class="card mb-3" style="max-width: 1080px;">
        <div class="row no-gutters">
            <div class="col-md-4">
                <img src="/media/{{ object.image|default:'img/default.jpg' }}" class="card-img" alt="{{ object.name }}">
            </div>
            <div class="col-md-8">
                <div class="card-body">
                    <h5 class="card-title">{{ object.name }}</h5>
                    <p class="card-text">
                        <small class="text-muted">{% get_verbose_field_name object 'category' %} :</small>
                        {{ object.category|title }}</p>
                    <p class="card-text">
                        <small class="text-muted">{% get_verbose_field_name object 'short_desc' %} :</small>
                        {{ object.short_desc }}</p>
                    <p class="card-text">
                        <small class="text-muted">{% get_verbose_field_name object 'desc' %} :</small>
                        {{ object.desc }}</p>
                    <p class="card-text">
                        <small class="text-muted">{% get_verbose_field_name object 'is_active' %} :</small>
                        {% if object.is_active %} Да {% else %} Нет {% endif %}</p>
                    <p class="card-text">
                        <small class="text-muted">{% get_verbose_field_name object 'price' %} :</small>
                        {{ object.price }}</p>
                    <p class="card-text">
                        <small class="text-muted">{% get_verbose_field_name object 'quantity' %} :</small>
                        {{ object.quantity }}</p>
                    <div class="d-flex justify-content-around">
                        <a href="{% url 'admin_staff:products' object.category.id %}"
                           class="btn btn-primary">Назад</a>
                        <a href="{% url 'admin_staff:product_update' object.id %}"
                           class="btn btn-warning">Редактировать</a>
                        <form action="{% url 'admin_staff:product_delete' product.id %}" method="POST">
                            {% csrf_token %}
                            {% if object.is_active %}
                                <button class="btn btn-danger">Удалить</button>
                            {% else %}
                                <button class="btn btn-danger disabled">Удалить</button>
                            {% endif %}
                        </form>
                    </div>

                </div>
            </div>
        </div>
    </div>
{% endblock %}

geekshop/adminapp/templates/adminapp/product_update.html
{% extends 'adminapp/base.html' %}
{% load static %}
{% block main_content %}
    <div class="col-5 mx-left">
        <div class="row">
            <form class="form-control" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <input class="form-control bnt-primary" type="submit" value="сохранить">
            </form>
            <button class="btn btn-round form-control last">
                {% if object.category.id %}
                    <a href="{% url 'admin_staff:products' object.category.id %}">
                        К списку продуктов
                    </a>
                {% else %}
                    <a href="{% url 'admin_staff:products' view.kwargs.pk %}">
                        К списку продуктов
                    </a>
                {% endif %}
            </button>
        </div>
    </div>
{% endblock %}

geekshop/adminapp/templates/adminapp/products.html
{% extends 'adminapp/base.html' %}
{% load static %}
{% block main_content %}
    <div class="row" style="justify-content:center">
        <div class="basket_list">
            <table class="table table-bordered table-hover caption-top align-middle text-center">
                <caption>
                    <a href="{% url 'admin_staff:product_create' view.kwargs.pk %}"
                       class="btn btn-primary">Добавить продукт</a>
                </caption>
                <thead class="table-dark">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Изображение</th>
                    <th scope="col">Категория</th>
                    <th scope="col">Имя</th>
                    <th scope="col">Цена</th>
                    <th scope="col">На складе</th>
                    <th scope="col">Опции</th>
                </tr>
                </thead>
                <tbody>
                {% for product in products %}
                    <tr {% if not product.is_active %} style="opacity: 0.5" {% endif %}>
                        <th scope="row">{{ forloop.counter }}</th>
                        <td><img src="/media/{{ product.image|default:'img/default.jpg' }}"
                                 alt="{{ product.short_desc }}" class="img-fluid" style="width: 25%"></td>
                        <td>{{ product.category.name }}</td>
                        <td>{{ product.name }}</td>
                        <td>{{ product.price }}&nbspруб</td>
                        <td><input type="number" min="0"
                                   value="{{ product.quantity }}"></td>
                        <td>
                            <div class="d-flex justify-content-around">
                                <form action="{% url 'admin_staff:product_read' product.id %}" method="GET">
                                    {% csrf_token %}
                                    <button class="btn btn-outline-primary">Детали</button>
                                </form>
                                <form action="{% url 'admin_staff:product_delete' product.id %}" method="POST">
                                    {% csrf_token %}
                                    {% if product.is_active %}
                                        <button class="btn btn-outline-danger">Удалить</button>
                                    {% else %}
                                        <button class="btn btn-outline-danger disabled">Удалить</button>
                                    {% endif %}
                                </form>
                            </div>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

geekshop/adminapp/templates/adminapp/user_update.html
{% extends 'adminapp/base.html' %}
{% load static %}
{% block main_content %}
    <div class="col-5 mx-left">
        <div class="row">
            <form class="form-control" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <input class="form-control bnt-primary" type="submit" value="сохранить">
            </form>
            <button class="btn btn-round form-control last">
                <a href="{% url 'admin_staff:users' %}">
                    К списку пользователей
                </a>
            </button>
        </div>
    </div>
{% endblock %}

geekshop/adminapp/templates/adminapp/users.html
{% extends 'adminapp/base.html' %}
{% load static %}
{% block main_content %}
    <table class="table table-bordered table-hover caption-top text-center">
        <caption>
            <a href="{% url 'admin_staff:user_create'%}"
                       class="btn btn-primary">Создать пользователя</a>
        </caption>
        <thead class="table-dark">
        <tr>
            <th scope="col">Логин</th>
            <th scope="col">Имя</th>
            <th scope="col">Фамилия</th>
            <th scope="col">E-mail</th>
            <th scope="col">Персонал сайта</th>
            <th scope="col">Активный</th>
            <th scope="col">Последний вход</th>
            <th scope="col">Опции</th>
        </tr>
        </thead>
        <tbody>
        {% for user in users_list %}
            <tr {% if not user.is_active %}style="opacity: 0.5"{% endif %}>
                <th class="align-middle" scope="row">
                    <a href="{% url 'admin_staff:user_update' user.id %}"
                       class="link-info">{{ user.username }}</a></th>
                <td class="align-middle">{{ user.first_name }}</td>
                <td class="align-middle">{{ user.last_name }}</td>
                <td class="align-middle">{{ user.email }}</td>
                <td class="align-middle text-center">
                    {% if user.is_staff %}
                        <i class="fa fa-check-circle"></i>
                    {% else %}
                        <i class="fa fa-times-circle"></i>
                    {% endif %}
                </td>
                <td class="align-middle">
                    {% if user.is_active %}
                        <i class="fa fa-check-circle"></i>
                    {% else %}
                        <i class="fa fa-times-circle"></i>
                    {% endif %}
                </td>
                <td class="align-middle">{{ user.last_login }}</td>
                <td class="align-middle">
                    <form action="{% url 'admin_staff:user_delete' user.id %}" method="POST">
                        {% csrf_token %}
                        {% if user.is_active %}
                        <button class="btn btn-outline-danger"> Удалить</button>
                        {% else %}
                        <button class="btn btn-outline-danger disabled"> Удалить</button>
                        {% endif %}
                    </form>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}